FROM golang:1.25-alpine

RUN apk add --no-cache git

# ติดตั้ง Air สำหรับ Hot Reload
RUN go install github.com/air-verse/air@latest

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

# เราจะไม่ COPY โค้ดที่นี่ เพราะเราจะใช้ Volume Mount จาก docker-compose แทน
# เพื่อให้เวลาเราแก้โค้ดในเครื่อง Docker จะเห็นทันที

CMD ["air", "-c", ".air.toml"]
