// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bikes.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createBike = `-- name: CreateBike :exec
INSERT INTO bikes (id, hardware_id, status, image_url)
VALUES ($1, $2, $3, $4)
`

type CreateBikeParams struct {
	ID         string
	HardwareID string
	Status     string
	ImageUrl   sql.NullString
}

func (q *Queries) CreateBike(ctx context.Context, arg CreateBikeParams) error {
	_, err := q.db.ExecContext(ctx, createBike,
		arg.ID,
		arg.HardwareID,
		arg.Status,
		arg.ImageUrl,
	)
	return err
}

const createBikeLocation = `-- name: CreateBikeLocation :exec
INSERT INTO bike_locations (id, bike_id, lat, lon, battery, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateBikeLocationParams struct {
	ID        uuid.UUID
	BikeID    string
	Lat       float64
	Lon       float64
	Battery   int32
	CreatedAt time.Time
}

func (q *Queries) CreateBikeLocation(ctx context.Context, arg CreateBikeLocationParams) error {
	_, err := q.db.ExecContext(ctx, createBikeLocation,
		arg.ID,
		arg.BikeID,
		arg.Lat,
		arg.Lon,
		arg.Battery,
		arg.CreatedAt,
	)
	return err
}

const getBike = `-- name: GetBike :one
SELECT id, hardware_id, lat, lon, battery_level, status, image_url, current_ride_id, last_heartbeat, created_at, updated_at FROM bikes WHERE id = $1
`

func (q *Queries) GetBike(ctx context.Context, id string) (Bike, error) {
	row := q.db.QueryRowContext(ctx, getBike, id)
	var i Bike
	err := row.Scan(
		&i.ID,
		&i.HardwareID,
		&i.Lat,
		&i.Lon,
		&i.BatteryLevel,
		&i.Status,
		&i.ImageUrl,
		&i.CurrentRideID,
		&i.LastHeartbeat,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllBikes = `-- name: ListAllBikes :many
SELECT id, hardware_id, lat, lon, battery_level, status, image_url, current_ride_id, last_heartbeat, created_at, updated_at FROM bikes ORDER BY id
`

func (q *Queries) ListAllBikes(ctx context.Context) ([]Bike, error) {
	rows, err := q.db.QueryContext(ctx, listAllBikes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bike
	for rows.Next() {
		var i Bike
		if err := rows.Scan(
			&i.ID,
			&i.HardwareID,
			&i.Lat,
			&i.Lon,
			&i.BatteryLevel,
			&i.Status,
			&i.ImageUrl,
			&i.CurrentRideID,
			&i.LastHeartbeat,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAvailableBikes = `-- name: ListAvailableBikes :many
SELECT id, hardware_id, lat, lon, battery_level, status, image_url, current_ride_id, last_heartbeat, created_at, updated_at FROM bikes 
WHERE status = 'available' 
AND battery_level > 20
ORDER BY id
`

func (q *Queries) ListAvailableBikes(ctx context.Context) ([]Bike, error) {
	rows, err := q.db.QueryContext(ctx, listAvailableBikes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bike
	for rows.Next() {
		var i Bike
		if err := rows.Scan(
			&i.ID,
			&i.HardwareID,
			&i.Lat,
			&i.Lon,
			&i.BatteryLevel,
			&i.Status,
			&i.ImageUrl,
			&i.CurrentRideID,
			&i.LastHeartbeat,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBikeRideStatus = `-- name: UpdateBikeRideStatus :exec
UPDATE bikes
SET status = $2,
    current_ride_id = $3,
    updated_at = NOW()
WHERE id = $1
`

type UpdateBikeRideStatusParams struct {
	ID            string
	Status        string
	CurrentRideID uuid.NullUUID
}

func (q *Queries) UpdateBikeRideStatus(ctx context.Context, arg UpdateBikeRideStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateBikeRideStatus, arg.ID, arg.Status, arg.CurrentRideID)
	return err
}

const updateBikeStatus = `-- name: UpdateBikeStatus :exec
UPDATE bikes
SET lat = $2,
    lon = $3,
    battery_level = $4,
    last_heartbeat = NOW(),
    updated_at = NOW()
WHERE id = $1
`

type UpdateBikeStatusParams struct {
	ID           string
	Lat          float64
	Lon          float64
	BatteryLevel int32
}

func (q *Queries) UpdateBikeStatus(ctx context.Context, arg UpdateBikeStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateBikeStatus,
		arg.ID,
		arg.Lat,
		arg.Lon,
		arg.BatteryLevel,
	)
	return err
}
