// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: configs.sql

package sqlc

import (
	"context"
)

const getConfig = `-- name: GetConfig :one
SELECT value FROM configs WHERE key = $1
`

func (q *Queries) GetConfig(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getConfig, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const setConfig = `-- name: SetConfig :exec
INSERT INTO configs (key, value, updated_at) 
VALUES ($1, $2, NOW()) 
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW()
`

type SetConfigParams struct {
	Key   string
	Value string
}

func (q *Queries) SetConfig(ctx context.Context, arg SetConfigParams) error {
	_, err := q.db.ExecContext(ctx, setConfig, arg.Key, arg.Value)
	return err
}
