// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: coupons.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const checkUserCouponUsed = `-- name: CheckUserCouponUsed :one
SELECT EXISTS(
    SELECT 1 FROM user_coupons WHERE user_id = $1 AND coupon_id = $2
)
`

type CheckUserCouponUsedParams struct {
	UserID   uuid.UUID
	CouponID uuid.UUID
}

func (q *Queries) CheckUserCouponUsed(ctx context.Context, arg CheckUserCouponUsedParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkUserCouponUsed, arg.UserID, arg.CouponID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createCoupon = `-- name: CreateCoupon :exec
INSERT INTO coupons (id, code, type, value, min_amount, start_at, max_uses, used_count, expired_at, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, 0, $8, NOW(), NOW())
`

type CreateCouponParams struct {
	ID        uuid.UUID
	Code      string
	Type      string
	Value     string
	MinAmount sql.NullString
	StartAt   time.Time
	MaxUses   int32
	ExpiredAt time.Time
}

func (q *Queries) CreateCoupon(ctx context.Context, arg CreateCouponParams) error {
	_, err := q.db.ExecContext(ctx, createCoupon,
		arg.ID,
		arg.Code,
		arg.Type,
		arg.Value,
		arg.MinAmount,
		arg.StartAt,
		arg.MaxUses,
		arg.ExpiredAt,
	)
	return err
}

const getAvailableDiscountCoupon = `-- name: GetAvailableDiscountCoupon :one
SELECT c.id, c.code, c.type, c.value, c.min_amount, c.start_at, c.max_uses, c.used_count, c.expired_at, c.created_at, c.updated_at, uc.id as user_coupon_id 
FROM user_coupons uc
JOIN coupons c ON uc.coupon_id = c.id
WHERE uc.user_id = $1 AND uc.is_used = FALSE AND c.type = 'discount'
ORDER BY c.value DESC LIMIT 1
`

type GetAvailableDiscountCouponRow struct {
	ID           uuid.UUID
	Code         string
	Type         string
	Value        string
	MinAmount    sql.NullString
	StartAt      time.Time
	MaxUses      int32
	UsedCount    int32
	ExpiredAt    time.Time
	CreatedAt    time.Time
	UpdatedAt    time.Time
	UserCouponID uuid.UUID
}

func (q *Queries) GetAvailableDiscountCoupon(ctx context.Context, userID uuid.UUID) (GetAvailableDiscountCouponRow, error) {
	row := q.db.QueryRowContext(ctx, getAvailableDiscountCoupon, userID)
	var i GetAvailableDiscountCouponRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Type,
		&i.Value,
		&i.MinAmount,
		&i.StartAt,
		&i.MaxUses,
		&i.UsedCount,
		&i.ExpiredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserCouponID,
	)
	return i, err
}

const getCouponByCode = `-- name: GetCouponByCode :one
SELECT id, code, type, value, min_amount, start_at, max_uses, used_count, expired_at, created_at, updated_at FROM coupons WHERE code = $1 LIMIT 1
`

func (q *Queries) GetCouponByCode(ctx context.Context, code string) (Coupon, error) {
	row := q.db.QueryRowContext(ctx, getCouponByCode, code)
	var i Coupon
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Type,
		&i.Value,
		&i.MinAmount,
		&i.StartAt,
		&i.MaxUses,
		&i.UsedCount,
		&i.ExpiredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMyAvailableCoupons = `-- name: GetMyAvailableCoupons :many
SELECT c.id, c.code, c.type, c.value, c.min_amount, c.start_at, c.max_uses, c.used_count, c.expired_at, c.created_at, c.updated_at, uc.id as user_coupon_id, uc.used_at as collected_at
FROM user_coupons uc
JOIN coupons c ON uc.coupon_id = c.id
WHERE uc.user_id = $1 AND uc.is_used = FALSE AND c.expired_at > NOW()
ORDER BY uc.used_at DESC
`

type GetMyAvailableCouponsRow struct {
	ID           uuid.UUID
	Code         string
	Type         string
	Value        string
	MinAmount    sql.NullString
	StartAt      time.Time
	MaxUses      int32
	UsedCount    int32
	ExpiredAt    time.Time
	CreatedAt    time.Time
	UpdatedAt    time.Time
	UserCouponID uuid.UUID
	CollectedAt  sql.NullTime
}

func (q *Queries) GetMyAvailableCoupons(ctx context.Context, userID uuid.UUID) ([]GetMyAvailableCouponsRow, error) {
	rows, err := q.db.QueryContext(ctx, getMyAvailableCoupons, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMyAvailableCouponsRow
	for rows.Next() {
		var i GetMyAvailableCouponsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Type,
			&i.Value,
			&i.MinAmount,
			&i.StartAt,
			&i.MaxUses,
			&i.UsedCount,
			&i.ExpiredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserCouponID,
			&i.CollectedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSpecificUserCouponByCode = `-- name: GetSpecificUserCouponByCode :one
SELECT c.id, c.code, c.type, c.value, c.min_amount, c.start_at, c.max_uses, c.used_count, c.expired_at, c.created_at, c.updated_at, uc.id as user_coupon_id 
FROM user_coupons uc
JOIN coupons c ON uc.coupon_id = c.id
WHERE uc.user_id = $1 AND c.code = $2 AND uc.is_used = FALSE AND c.type = 'discount'
LIMIT 1
`

type GetSpecificUserCouponByCodeParams struct {
	UserID uuid.UUID
	Code   string
}

type GetSpecificUserCouponByCodeRow struct {
	ID           uuid.UUID
	Code         string
	Type         string
	Value        string
	MinAmount    sql.NullString
	StartAt      time.Time
	MaxUses      int32
	UsedCount    int32
	ExpiredAt    time.Time
	CreatedAt    time.Time
	UpdatedAt    time.Time
	UserCouponID uuid.UUID
}

func (q *Queries) GetSpecificUserCouponByCode(ctx context.Context, arg GetSpecificUserCouponByCodeParams) (GetSpecificUserCouponByCodeRow, error) {
	row := q.db.QueryRowContext(ctx, getSpecificUserCouponByCode, arg.UserID, arg.Code)
	var i GetSpecificUserCouponByCodeRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Type,
		&i.Value,
		&i.MinAmount,
		&i.StartAt,
		&i.MaxUses,
		&i.UsedCount,
		&i.ExpiredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserCouponID,
	)
	return i, err
}

const incrementCouponUsedCount = `-- name: IncrementCouponUsedCount :exec
UPDATE coupons SET used_count = used_count + 1, updated_at = NOW() WHERE id = $1
`

func (q *Queries) IncrementCouponUsedCount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, incrementCouponUsedCount, id)
	return err
}

const markUserCouponAsUsed = `-- name: MarkUserCouponAsUsed :exec
UPDATE user_coupons SET is_used = TRUE, used_at = NOW() WHERE id = $1
`

func (q *Queries) MarkUserCouponAsUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markUserCouponAsUsed, id)
	return err
}

const recordUserCoupon = `-- name: RecordUserCoupon :exec
INSERT INTO user_coupons (id, user_id, coupon_id, is_used, used_at)
VALUES ($1, $2, $3, $4, $5)
`

type RecordUserCouponParams struct {
	ID       uuid.UUID
	UserID   uuid.UUID
	CouponID uuid.UUID
	IsUsed   bool
	UsedAt   sql.NullTime
}

func (q *Queries) RecordUserCoupon(ctx context.Context, arg RecordUserCouponParams) error {
	_, err := q.db.ExecContext(ctx, recordUserCoupon,
		arg.ID,
		arg.UserID,
		arg.CouponID,
		arg.IsUsed,
		arg.UsedAt,
	)
	return err
}
