// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Bike struct {
	ID            string
	HardwareID    string
	Status        string
	Lat           float64
	Lon           float64
	BatteryLevel  int32
	ImageUrl      sql.NullString
	LastHeartbeat sql.NullTime
	CurrentRideID uuid.NullUUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type BikeLocation struct {
	ID        uuid.UUID
	BikeID    string
	Lat       float64
	Lon       float64
	Battery   int32
	CreatedAt time.Time
}

type Config struct {
	Key         string
	Value       string
	Description sql.NullString
	UpdatedAt   time.Time
}

type Coupon struct {
	ID        uuid.UUID
	Code      string
	Type      string
	Value     string
	MinAmount sql.NullString
	StartAt   time.Time
	MaxUses   int32
	UsedCount int32
	ExpiredAt time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Notification struct {
	ID        uuid.UUID
	UserID    uuid.NullUUID
	Title     string
	Message   string
	Type      string
	IsRead    bool
	CreatedAt time.Time
}

type Report struct {
	ID         uuid.UUID
	BikeID     string
	ReportedBy uuid.UUID
	IssueType  string
	Status     string
	ResolvedBy uuid.NullUUID
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Ride struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	BikeID     string
	StartLat   float64
	StartLon   float64
	EndLat     sql.NullFloat64
	EndLon     sql.NullFloat64
	DistanceKm float64
	TotalFare  string
	Status     string
	Type       string
	StartTime  time.Time
	EndTime    sql.NullTime
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Transaction struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Amount      string
	Type        string
	Status      string
	ReferenceID sql.NullString
	GatewayRef  sql.NullString
	Description sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type User struct {
	ID            uuid.UUID
	PhoneNumber   string
	Username      string
	Password      string
	WalletBalance string
	Role          string
	Status        string
	ImageUrl      sql.NullString
	FcmToken      sql.NullString
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type UserCoupon struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	CouponID  uuid.UUID
	IsUsed    bool
	UsedAt    sql.NullTime
	CreatedAt time.Time
}

type UserMonthlySpending struct {
	UserID    uuid.UUID
	YearMonth int32
	Amount    string
	UpdatedAt time.Time
}

type Zone struct {
	ID        uuid.UUID
	Name      string
	Type      string
	Boundary  string
	Radius    float64
	CreatedAt time.Time
	UpdatedAt time.Time
}
