// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Bike struct {
	ID            string
	HardwareID    string
	Lat           float64
	Lon           float64
	BatteryLevel  int32
	Status        string
	ImageUrl      sql.NullString
	CurrentRideID uuid.NullUUID
	LastHeartbeat time.Time
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type BikeLocation struct {
	ID        uuid.UUID
	BikeID    string
	Lat       float64
	Lon       float64
	Battery   int32
	CreatedAt time.Time
}

type Config struct {
	Key       string
	Value     string
	UpdatedAt time.Time
}

type Report struct {
	ID         uuid.UUID
	BikeID     string
	ReportedBy uuid.UUID
	IssueType  string
	Status     string
	ResolvedBy uuid.NullUUID
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Ride struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	BikeID     string
	StartTime  time.Time
	EndTime    sql.NullTime
	StartLat   float64
	StartLon   float64
	EndLat     sql.NullFloat64
	EndLon     sql.NullFloat64
	DistanceKm sql.NullFloat64
	TotalFare  sql.NullString
	Status     string
	Type       string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Transaction struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Amount      string
	Type        string
	Status      string
	ReferenceID uuid.NullUUID
	GatewayRef  sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type User struct {
	ID            uuid.UUID
	PhoneNumber   string
	Username      string
	Password      string
	WalletBalance string
	Role          string
	Status        string
	ImageUrl      sql.NullString
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type UserMonthlySpending struct {
	UserID    uuid.UUID
	YearMonth int32
	Amount    string
	UpdatedAt time.Time
}

type Zone struct {
	ID        uuid.UUID
	Name      string
	Type      string
	Boundary  pqtype.NullRawMessage
	Radius    sql.NullFloat64
	CreatedAt time.Time
	UpdatedAt time.Time
}
