// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createNotification = `-- name: CreateNotification :exec
INSERT INTO notifications (id, user_id, title, message, type, is_read, created_at)
VALUES ($1, $2, $3, $4, $5, FALSE, NOW())
`

type CreateNotificationParams struct {
	ID      uuid.UUID
	UserID  uuid.NullUUID
	Title   string
	Message string
	Type    string
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) error {
	_, err := q.db.ExecContext(ctx, createNotification,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Message,
		arg.Type,
	)
	return err
}

const getMyNotifications = `-- name: GetMyNotifications :many
SELECT id, user_id, title, message, type, is_read, created_at FROM notifications 
WHERE user_id = $1 OR user_id IS NULL
ORDER BY created_at DESC
`

func (q *Queries) GetMyNotifications(ctx context.Context, userID uuid.NullUUID) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, getMyNotifications, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Message,
			&i.Type,
			&i.IsRead,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationAsRead = `-- name: MarkNotificationAsRead :exec
UPDATE notifications SET is_read = TRUE WHERE id = $1 AND user_id = $2
`

type MarkNotificationAsReadParams struct {
	ID     uuid.UUID
	UserID uuid.NullUUID
}

func (q *Queries) MarkNotificationAsRead(ctx context.Context, arg MarkNotificationAsReadParams) error {
	_, err := q.db.ExecContext(ctx, markNotificationAsRead, arg.ID, arg.UserID)
	return err
}

const updateUserFCMToken = `-- name: UpdateUserFCMToken :exec
UPDATE users SET fcm_token = $2, updated_at = NOW() WHERE id = $1
`

type UpdateUserFCMTokenParams struct {
	ID       uuid.UUID
	FcmToken sql.NullString
}

func (q *Queries) UpdateUserFCMToken(ctx context.Context, arg UpdateUserFCMTokenParams) error {
	_, err := q.db.ExecContext(ctx, updateUserFCMToken, arg.ID, arg.FcmToken)
	return err
}
