// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reports.sql

package sqlc

import (
	"context"
	"time"
)

const getBikeUsageStats = `-- name: GetBikeUsageStats :many
SELECT 
    bike_id, 
    COUNT(*) as ride_count,
    COALESCE(SUM(distance_km), 0)::FLOAT as total_distance_km,
    COALESCE(SUM(CAST(total_fare AS DECIMAL)), 0)::TEXT as total_revenue
FROM rides
WHERE status = 'completed'
GROUP BY bike_id
ORDER BY ride_count DESC
`

type GetBikeUsageStatsRow struct {
	BikeID          string
	RideCount       int64
	TotalDistanceKm float64
	TotalRevenue    string
}

func (q *Queries) GetBikeUsageStats(ctx context.Context) ([]GetBikeUsageStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, getBikeUsageStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBikeUsageStatsRow
	for rows.Next() {
		var i GetBikeUsageStatsRow
		if err := rows.Scan(
			&i.BikeID,
			&i.RideCount,
			&i.TotalDistanceKm,
			&i.TotalRevenue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDailyRevenue = `-- name: GetDailyRevenue :many
SELECT 
    DATE(start_time) as date,
    COUNT(*) as ride_count,
    COALESCE(SUM(CAST(total_fare AS DECIMAL)), 0)::TEXT as daily_revenue
FROM rides
WHERE status = 'completed'
GROUP BY DATE(start_time)
ORDER BY date DESC
LIMIT 7
`

type GetDailyRevenueRow struct {
	Date         time.Time
	RideCount    int64
	DailyRevenue string
}

func (q *Queries) GetDailyRevenue(ctx context.Context) ([]GetDailyRevenueRow, error) {
	rows, err := q.db.QueryContext(ctx, getDailyRevenue)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDailyRevenueRow
	for rows.Next() {
		var i GetDailyRevenueRow
		if err := rows.Scan(&i.Date, &i.RideCount, &i.DailyRevenue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSystemSummary = `-- name: GetSystemSummary :one
SELECT 
    (SELECT COUNT(*) FROM users WHERE role = 'user') as total_users,
    (SELECT COUNT(*) FROM bikes) as total_bikes,
    (SELECT COUNT(*) FROM bikes WHERE status = 'available') as available_bikes,
    (SELECT COUNT(*) FROM rides WHERE status = 'ongoing') as active_rides,
    (SELECT COALESCE(SUM(CAST(total_fare AS DECIMAL)), 0)::TEXT FROM rides WHERE status = 'completed') as total_revenue
FROM rides LIMIT 1
`

type GetSystemSummaryRow struct {
	TotalUsers     int64
	TotalBikes     int64
	AvailableBikes int64
	ActiveRides    int64
	TotalRevenue   string
}

func (q *Queries) GetSystemSummary(ctx context.Context) (GetSystemSummaryRow, error) {
	row := q.db.QueryRowContext(ctx, getSystemSummary)
	var i GetSystemSummaryRow
	err := row.Scan(
		&i.TotalUsers,
		&i.TotalBikes,
		&i.AvailableBikes,
		&i.ActiveRides,
		&i.TotalRevenue,
	)
	return i, err
}
