// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reports.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createReport = `-- name: CreateReport :exec
INSERT INTO reports (id, bike_id, reported_by, issue_type, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, NOW(), NOW())
`

type CreateReportParams struct {
	ID         uuid.UUID
	BikeID     string
	ReportedBy uuid.UUID
	IssueType  string
	Status     string
}

func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) error {
	_, err := q.db.ExecContext(ctx, createReport,
		arg.ID,
		arg.BikeID,
		arg.ReportedBy,
		arg.IssueType,
		arg.Status,
	)
	return err
}

const getReport = `-- name: GetReport :one
SELECT id, bike_id, reported_by, issue_type, status, resolved_by, created_at, updated_at FROM reports WHERE id = $1
`

func (q *Queries) GetReport(ctx context.Context, id uuid.UUID) (Report, error) {
	row := q.db.QueryRowContext(ctx, getReport, id)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.BikeID,
		&i.ReportedBy,
		&i.IssueType,
		&i.Status,
		&i.ResolvedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listReportsByBike = `-- name: ListReportsByBike :many
SELECT id, bike_id, reported_by, issue_type, status, resolved_by, created_at, updated_at FROM reports WHERE bike_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListReportsByBike(ctx context.Context, bikeID string) ([]Report, error) {
	rows, err := q.db.QueryContext(ctx, listReportsByBike, bikeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Report
	for rows.Next() {
		var i Report
		if err := rows.Scan(
			&i.ID,
			&i.BikeID,
			&i.ReportedBy,
			&i.IssueType,
			&i.Status,
			&i.ResolvedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReportsByStatus = `-- name: ListReportsByStatus :many
SELECT id, bike_id, reported_by, issue_type, status, resolved_by, created_at, updated_at FROM reports WHERE status = $1 ORDER BY created_at DESC
`

func (q *Queries) ListReportsByStatus(ctx context.Context, status string) ([]Report, error) {
	rows, err := q.db.QueryContext(ctx, listReportsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Report
	for rows.Next() {
		var i Report
		if err := rows.Scan(
			&i.ID,
			&i.BikeID,
			&i.ReportedBy,
			&i.IssueType,
			&i.Status,
			&i.ResolvedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReportStatus = `-- name: UpdateReportStatus :exec
UPDATE reports 
SET status = $2, 
    resolved_by = $3, 
    updated_at = NOW() 
WHERE id = $1
`

type UpdateReportStatusParams struct {
	ID         uuid.UUID
	Status     string
	ResolvedBy uuid.NullUUID
}

func (q *Queries) UpdateReportStatus(ctx context.Context, arg UpdateReportStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateReportStatus, arg.ID, arg.Status, arg.ResolvedBy)
	return err
}
