// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rides.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createRide = `-- name: CreateRide :exec
INSERT INTO rides (
    id, user_id, bike_id, start_time, start_lat, start_lon, status, type, created_at, updated_at
) VALUES (
    $1, $2, $3, NOW(), $4, $5, 'ongoing', $6, NOW(), NOW()
)
`

type CreateRideParams struct {
	ID       uuid.UUID
	UserID   uuid.UUID
	BikeID   string
	StartLat float64
	StartLon float64
	Type     string
}

func (q *Queries) CreateRide(ctx context.Context, arg CreateRideParams) error {
	_, err := q.db.ExecContext(ctx, createRide,
		arg.ID,
		arg.UserID,
		arg.BikeID,
		arg.StartLat,
		arg.StartLon,
		arg.Type,
	)
	return err
}

const endRide = `-- name: EndRide :exec
UPDATE rides
SET end_time = NOW(),
    end_lat = $2,
    end_lon = $3,
    distance_km = $4,
    total_fare = $5,
    status = 'completed',
    updated_at = NOW()
WHERE id = $1
`

type EndRideParams struct {
	ID         uuid.UUID
	EndLat     sql.NullFloat64
	EndLon     sql.NullFloat64
	DistanceKm float64
	TotalFare  string
}

func (q *Queries) EndRide(ctx context.Context, arg EndRideParams) error {
	_, err := q.db.ExecContext(ctx, endRide,
		arg.ID,
		arg.EndLat,
		arg.EndLon,
		arg.DistanceKm,
		arg.TotalFare,
	)
	return err
}

const getActiveRideByUser = `-- name: GetActiveRideByUser :one
SELECT id, user_id, bike_id, start_lat, start_lon, end_lat, end_lon, distance_km, total_fare, status, type, start_time, end_time, created_at, updated_at FROM rides WHERE user_id = $1 AND status = 'ongoing' LIMIT 1
`

func (q *Queries) GetActiveRideByUser(ctx context.Context, userID uuid.UUID) (Ride, error) {
	row := q.db.QueryRowContext(ctx, getActiveRideByUser, userID)
	var i Ride
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BikeID,
		&i.StartLat,
		&i.StartLon,
		&i.EndLat,
		&i.EndLon,
		&i.DistanceKm,
		&i.TotalFare,
		&i.Status,
		&i.Type,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRide = `-- name: GetRide :one
SELECT id, user_id, bike_id, start_lat, start_lon, end_lat, end_lon, distance_km, total_fare, status, type, start_time, end_time, created_at, updated_at FROM rides WHERE id = $1
`

func (q *Queries) GetRide(ctx context.Context, id uuid.UUID) (Ride, error) {
	row := q.db.QueryRowContext(ctx, getRide, id)
	var i Ride
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BikeID,
		&i.StartLat,
		&i.StartLon,
		&i.EndLat,
		&i.EndLon,
		&i.DistanceKm,
		&i.TotalFare,
		&i.Status,
		&i.Type,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRidesByUser = `-- name: ListRidesByUser :many
SELECT id, user_id, bike_id, start_lat, start_lon, end_lat, end_lon, distance_km, total_fare, status, type, start_time, end_time, created_at, updated_at FROM rides WHERE user_id = $1 ORDER BY start_time DESC
`

func (q *Queries) ListRidesByUser(ctx context.Context, userID uuid.UUID) ([]Ride, error) {
	rows, err := q.db.QueryContext(ctx, listRidesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ride
	for rows.Next() {
		var i Ride
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BikeID,
			&i.StartLat,
			&i.StartLon,
			&i.EndLat,
			&i.EndLon,
			&i.DistanceKm,
			&i.TotalFare,
			&i.Status,
			&i.Type,
			&i.StartTime,
			&i.EndTime,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
