// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_monthly_spending.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const addMonthlySpending = `-- name: AddMonthlySpending :exec
INSERT INTO user_monthly_spending (user_id, year_month, amount, updated_at)
VALUES ($1, $2, $3, NOW())
ON CONFLICT (user_id, year_month)
DO UPDATE SET 
    amount = user_monthly_spending.amount + EXCLUDED.amount,
    updated_at = NOW()
`

type AddMonthlySpendingParams struct {
	UserID    uuid.UUID
	YearMonth int32
	Amount    string
}

func (q *Queries) AddMonthlySpending(ctx context.Context, arg AddMonthlySpendingParams) error {
	_, err := q.db.ExecContext(ctx, addMonthlySpending, arg.UserID, arg.YearMonth, arg.Amount)
	return err
}

const getTotalSpendingFromSummary = `-- name: GetTotalSpendingFromSummary :one
SELECT COALESCE(SUM(amount), 0)::TEXT
FROM user_monthly_spending
WHERE user_id = $1 AND year_month >= $2
`

type GetTotalSpendingFromSummaryParams struct {
	UserID    uuid.UUID
	YearMonth int32
}

func (q *Queries) GetTotalSpendingFromSummary(ctx context.Context, arg GetTotalSpendingFromSummaryParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getTotalSpendingFromSummary, arg.UserID, arg.YearMonth)
	var column_1 string
	err := row.Scan(&column_1)
	return column_1, err
}
