// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: zones.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createZone = `-- name: CreateZone :exec
INSERT INTO zones (
    id, name, type, boundary, radius, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, NOW(), NOW()
)
`

type CreateZoneParams struct {
	ID       uuid.UUID
	Name     string
	Type     string
	Boundary pqtype.NullRawMessage
	Radius   sql.NullFloat64
}

func (q *Queries) CreateZone(ctx context.Context, arg CreateZoneParams) error {
	_, err := q.db.ExecContext(ctx, createZone,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.Boundary,
		arg.Radius,
	)
	return err
}

const deleteZone = `-- name: DeleteZone :exec
DELETE FROM zones WHERE id = $1
`

func (q *Queries) DeleteZone(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteZone, id)
	return err
}

const getZone = `-- name: GetZone :one
SELECT id, name, type, boundary, radius, created_at, updated_at FROM zones WHERE id = $1
`

func (q *Queries) GetZone(ctx context.Context, id uuid.UUID) (Zone, error) {
	row := q.db.QueryRowContext(ctx, getZone, id)
	var i Zone
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Boundary,
		&i.Radius,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listZones = `-- name: ListZones :many
SELECT id, name, type, boundary, radius, created_at, updated_at FROM zones ORDER BY name
`

func (q *Queries) ListZones(ctx context.Context) ([]Zone, error) {
	rows, err := q.db.QueryContext(ctx, listZones)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Zone
	for rows.Next() {
		var i Zone
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Boundary,
			&i.Radius,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listZonesByType = `-- name: ListZonesByType :many
SELECT id, name, type, boundary, radius, created_at, updated_at FROM zones WHERE type = $1 ORDER BY name
`

func (q *Queries) ListZonesByType(ctx context.Context, type_ string) ([]Zone, error) {
	rows, err := q.db.QueryContext(ctx, listZonesByType, type_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Zone
	for rows.Next() {
		var i Zone
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Boundary,
			&i.Radius,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateZone = `-- name: UpdateZone :exec
UPDATE zones
SET name = $2,
    type = $3,
    boundary = $4,
    radius = $5,
    updated_at = NOW()
WHERE id = $1
`

type UpdateZoneParams struct {
	ID       uuid.UUID
	Name     string
	Type     string
	Boundary pqtype.NullRawMessage
	Radius   sql.NullFloat64
}

func (q *Queries) UpdateZone(ctx context.Context, arg UpdateZoneParams) error {
	_, err := q.db.ExecContext(ctx, updateZone,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.Boundary,
		arg.Radius,
	)
	return err
}
