// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/admin/notifications/broadcast": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "แอดมินส่งประกาศ Ads หรือข่าวสารหาผู้ใช้ทุกคน",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Notifications"
                ],
                "summary": "Broadcast Notification (Admin Only)",
                "parameters": [
                    {
                        "description": "เนื้อหาประกาศ",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/broadcast.Request"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/bikes": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get a list of bikes based on user role. Normal users see available bikes only. Staff/Admin see all.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Bikes"
                ],
                "summary": "List Bikes",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entity.BikeData"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Add a new bike to the system.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Bikes"
                ],
                "summary": "Create New Bike (Admin)",
                "parameters": [
                    {
                        "description": "Bike creation request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_app_usecase_bike_create.Request"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/v1/bikes/{id}/status": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update bike status manually (e.g., to maintenance). Staff/Admin Only.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Bikes"
                ],
                "summary": "Update Bike Status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bike ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "New Status",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/update_status.Request"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/configs": {
            "post": {
                "description": "Set a global configuration value (e.g. parking_penalty_fee).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Configs"
                ],
                "summary": "Set System Config (Admin)",
                "parameters": [
                    {
                        "description": "Config request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/config.Request"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/v1/configs/{key}": {
            "get": {
                "description": "Get a global configuration value by key.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Configs"
                ],
                "summary": "Get System Config",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Config Key",
                        "name": "key",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/v1/coupons": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "แอดมินสร้างคูปองใหม่ กำหนดโค้ด ประเภท และมูลค่าได้เอง",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Coupons"
                ],
                "summary": "Create Coupon (Admin Only)",
                "parameters": [
                    {
                        "description": "รายละเอียดคูปอง",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_app_usecase_coupon_create.Request"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/coupons/my": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "ดึงรายการคูปองที่ผู้ใช้เก็บไว้และยังไม่ได้ใช้",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Coupons"
                ],
                "summary": "รายการคูปองของฉัน",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/list_my.CouponInfo"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/coupons/redeem": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "ใช้โค้ดส่วนลด หรือ โค้ดรับเงินฟรี",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Coupons"
                ],
                "summary": "Redeem Coupon",
                "parameters": [
                    {
                        "description": "โค้ดคูปอง",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/redeem.Request"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/notifications": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "ดึงประวัติการแจ้งเตือนทั้งหมด (ทั้ง Ads และส่วนตัว)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Notifications"
                ],
                "summary": "รายการแจ้งเตือนของฉัน",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/list.NotificationInfo"
                            }
                        }
                    }
                }
            }
        },
        "/v1/notifications/fcm-token": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "อัปเดต Token สำหรับส่ง Push Notification",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Notifications"
                ],
                "summary": "Update FCM Token",
                "parameters": [
                    {
                        "description": "FCM Token",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/update_token.Request"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/reports/summary": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get system-wide reports including revenue and usage stats. Admin Only.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Reports"
                ],
                "summary": "System Report Summary",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.FullReport"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/rides/end": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Stop the current ride and calculate fare.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Rides"
                ],
                "summary": "End Ride (Return Bike)",
                "parameters": [
                    {
                        "description": "End ride request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/end.Request"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.Ride"
                        }
                    }
                }
            }
        },
        "/v1/rides/start": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Start a new ride by scanning a bike QR code.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Rides"
                ],
                "summary": "Start Ride (Rent Bike)",
                "parameters": [
                    {
                        "description": "Start ride request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/start.Request"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/entity.Ride"
                        }
                    }
                }
            }
        },
        "/v1/users": {
            "post": {
                "description": "Register a new user with phone number, username, and password. After success, an OTP will be sent.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Create a new user (and send OTP)",
                "parameters": [
                    {
                        "description": "User creation request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_app_usecase_user_create.Request"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "User created pending, OTP sent",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Invalid request or validation failed",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/v1/users/login": {
            "post": {
                "description": "Login with username and password to receive a JWT token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Login User",
                "parameters": [
                    {
                        "description": "Login request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/login.Request"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully logged in",
                        "schema": {
                            "$ref": "#/definitions/login.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/v1/users/logout": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Logout the current user by instructing the client to clear the JWT token.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Logout User",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/v1/users/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get currently logged-in user profile from JWT token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Get My Profile",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/me.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/v1/users/profile/image": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update the profile image URL for the current user.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Update Profile Image",
                "parameters": [
                    {
                        "description": "Update profile image request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/update_profile.Request"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/v1/users/rank": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get current rank and spending progress for the last 4 months.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Get User Rank",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rank.Response"
                        }
                    }
                }
            }
        },
        "/v1/users/verify/firebase": {
            "post": {
                "description": "Verify the idToken received from Firebase on Frontend to activate the user account.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Verify Firebase Token and Activate User",
                "parameters": [
                    {
                        "description": "Firebase verification request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/verify_firebase.Request"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User activated successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Invalid token or request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/v1/wallet/topup": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates a new top-up transaction and returns a PromptPay QR code.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Wallet"
                ],
                "summary": "Request Wallet Top-up",
                "parameters": [
                    {
                        "description": "Topup Request (Amount)",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/topup.Request"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/topup.Response"
                        }
                    }
                }
            }
        },
        "/v1/wallet/transfer": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Transfer money to another user by phone number.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Wallet"
                ],
                "summary": "Wallet Transfer",
                "parameters": [
                    {
                        "description": "Transfer Details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/transfer.Request"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/wallet/verify-receiver": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Find username by phone number for wallet transfer.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Wallet"
                ],
                "summary": "Verify Receiver",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Receiver Phone Number",
                        "name": "phone",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/verify_receiver.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/wallet/webhook/paysolutions": {
            "post": {
                "description": "Receives payment status updates from PaySolutions server.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Wallet"
                ],
                "summary": "PaySolutions Webhook Callback",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/v1/zones": {
            "get": {
                "description": "Get a list of all service areas and parking zones.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Zones"
                ],
                "summary": "List All Zones",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entity.Zone"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new Parking Zone (P) or Riding Area (Area).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Zones"
                ],
                "summary": "Create New Zone (Admin)",
                "parameters": [
                    {
                        "description": "Zone creation request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_app_usecase_zone_create.Request"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "broadcast.Request": {
            "type": "object",
            "required": [
                "message",
                "title",
                "type"
            ],
            "properties": {
                "message": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "description": "promo, news, system",
                    "type": "string"
                }
            }
        },
        "config.Request": {
            "type": "object",
            "required": [
                "key",
                "value"
            ],
            "properties": {
                "key": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "end.Request": {
            "type": "object",
            "required": [
                "user_id"
            ],
            "properties": {
                "coupon_code": {
                    "description": "เพิ่มฟิลด์เลือกใช้คูปอง (Optional)",
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "entity.BikeData": {
            "type": "object",
            "properties": {
                "battery": {
                    "type": "integer"
                },
                "bike_id": {
                    "type": "string"
                },
                "current_ride_id": {
                    "type": "string"
                },
                "hardware_id": {
                    "type": "string"
                },
                "image_url": {
                    "type": "string"
                },
                "last_heartbeat": {
                    "type": "string"
                },
                "lat": {
                    "type": "number"
                },
                "lon": {
                    "type": "number"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "entity.BikeUsageStat": {
            "type": "object",
            "properties": {
                "bike_id": {
                    "type": "string"
                },
                "ride_count": {
                    "type": "integer"
                },
                "total_distance_km": {
                    "type": "number"
                },
                "total_revenue": {
                    "type": "string"
                }
            }
        },
        "entity.DailyRevenue": {
            "type": "object",
            "properties": {
                "daily_revenue": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "ride_count": {
                    "type": "integer"
                }
            }
        },
        "entity.FullReport": {
            "type": "object",
            "properties": {
                "bike_stats": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.BikeUsageStat"
                    }
                },
                "daily_revenue": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.DailyRevenue"
                    }
                },
                "summary": {
                    "$ref": "#/definitions/entity.SystemSummary"
                }
            }
        },
        "entity.Ride": {
            "type": "object",
            "properties": {
                "bikeID": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "distanceKm": {
                    "type": "number",
                    "format": "float64"
                },
                "endLat": {
                    "type": "number",
                    "format": "float64"
                },
                "endLon": {
                    "type": "number",
                    "format": "float64"
                },
                "endTime": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "startLat": {
                    "type": "number",
                    "format": "float64"
                },
                "startLon": {
                    "type": "number",
                    "format": "float64"
                },
                "startTime": {
                    "type": "string"
                },
                "status": {
                    "description": "ongoing, completed, cancelled",
                    "type": "string"
                },
                "totalFare": {
                    "type": "string"
                },
                "type": {
                    "description": "ride, service",
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "userID": {
                    "type": "string"
                }
            }
        },
        "entity.SystemSummary": {
            "type": "object",
            "properties": {
                "active_rides": {
                    "type": "integer"
                },
                "available_bikes": {
                    "type": "integer"
                },
                "total_bikes": {
                    "type": "integer"
                },
                "total_revenue": {
                    "type": "string"
                },
                "total_users": {
                    "type": "integer"
                }
            }
        },
        "entity.Zone": {
            "type": "object",
            "properties": {
                "boundary": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "radius": {
                    "type": "number",
                    "format": "float64"
                },
                "type": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "geo.Point": {
            "type": "object",
            "properties": {
                "lat": {
                    "type": "number"
                },
                "lon": {
                    "type": "number"
                }
            }
        },
        "internal_app_usecase_bike_create.Request": {
            "type": "object",
            "required": [
                "bike_id",
                "hardware_id"
            ],
            "properties": {
                "bike_id": {
                    "type": "string"
                },
                "hardware_id": {
                    "type": "string"
                },
                "image_url": {
                    "type": "string"
                }
            }
        },
        "internal_app_usecase_coupon_create.Request": {
            "type": "object",
            "required": [
                "code",
                "expired_at",
                "max_uses",
                "type",
                "value"
            ],
            "properties": {
                "code": {
                    "type": "string"
                },
                "expired_at": {
                    "type": "string"
                },
                "max_uses": {
                    "type": "integer"
                },
                "min_amount": {
                    "type": "string"
                },
                "start_at": {
                    "type": "string"
                },
                "type": {
                    "description": "credit, discount",
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "internal_app_usecase_user_create.Request": {
            "type": "object",
            "required": [
                "password",
                "phone_number",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "minLength": 6,
                    "example": "password123"
                },
                "phone_number": {
                    "type": "string",
                    "minLength": 10,
                    "example": "0812345678"
                },
                "username": {
                    "type": "string",
                    "minLength": 2,
                    "example": "somchai_jaidee"
                }
            }
        },
        "internal_app_usecase_zone_create.Request": {
            "type": "object",
            "required": [
                "name",
                "type"
            ],
            "properties": {
                "boundary": {
                    "description": "ขอบเขต Polygon",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/geo.Point"
                    }
                },
                "name": {
                    "type": "string"
                },
                "radius": {
                    "description": "ถ้าระบุ Radius จะใช้เป็นวงกลม (ใช้พิกัดแรกใน Boundary เป็นจุดศูนย์กลาง)",
                    "type": "number"
                },
                "type": {
                    "description": "\"P\" หรือ \"Area\"",
                    "type": "string"
                }
            }
        },
        "list.NotificationInfo": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_read": {
                    "type": "boolean"
                },
                "message": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "list_my.CouponInfo": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "collected_at": {
                    "type": "string"
                },
                "expired_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "min_amount": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "user_coupon_id": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "login.Request": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "example": "password123"
                },
                "username": {
                    "type": "string",
                    "example": "somchai_jaidee"
                }
            }
        },
        "login.Response": {
            "type": "object",
            "properties": {
                "role": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "me.Response": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "rank.Response": {
            "type": "object",
            "properties": {
                "current_discount": {
                    "type": "number"
                },
                "current_rank": {
                    "type": "string"
                },
                "next_rank_threshold": {
                    "type": "number"
                },
                "progress_percentage": {
                    "type": "number"
                },
                "total_spent_4_months": {
                    "type": "number"
                }
            }
        },
        "redeem.Request": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "start.Request": {
            "type": "object",
            "required": [
                "bike_id",
                "user_id"
            ],
            "properties": {
                "bike_id": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "topup.Request": {
            "type": "object",
            "required": [
                "amount"
            ],
            "properties": {
                "amount": {
                    "type": "number"
                }
            }
        },
        "topup.Response": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "qr_code_url": {
                    "type": "string"
                },
                "transaction_id": {
                    "type": "string"
                }
            }
        },
        "transfer.Request": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "receiver_phone": {
                    "type": "string"
                },
                "sender_id": {
                    "type": "string"
                }
            }
        },
        "update_profile.Request": {
            "type": "object",
            "required": [
                "image_url"
            ],
            "properties": {
                "image_url": {
                    "type": "string"
                }
            }
        },
        "update_status.Request": {
            "type": "object",
            "properties": {
                "bike_id": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "update_token.Request": {
            "type": "object",
            "required": [
                "fcm_token"
            ],
            "properties": {
                "fcm_token": {
                    "type": "string"
                }
            }
        },
        "verify_firebase.Request": {
            "type": "object",
            "required": [
                "id_token"
            ],
            "properties": {
                "id_token": {
                    "type": "string"
                }
            }
        },
        "verify_receiver.Response": {
            "type": "object",
            "properties": {
                "phone_number": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type 'Bearer ' followed by your JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Bidkan Backend API",
	Description:      "This is a sample server for Bidkan Clean Architecture.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
